name: Scraping and Database Saving

on:
  push:
  workflow_dispatch: 
  schedule:
    - cron: '20 8 * * *' 
    
# lets gh change files
permissions: write-all

jobs:
  run: 
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Create data directory
        run: mkdir -p data

      - name: Run Python script
        run: python hm_scrape.py > data/$(date +%Y%m%d-%H%M%S).txt

      - name: Add data to the repository
        run: |
                git config user.name 'GitHub Actions'
                git config user.email 'actions@users.noreply.github.com'
                git add -A
                git commit -m 'Updates' || exit 0
                git push
