name: Scraping and Database Saving

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9am UK time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests beautifulsoup4

    - name: Run Python script
      run: python hm_scrape.py

    - name: Create database folder
      run: mkdir database

    - name: Save database file
      run: mv hm_sustainability_database.csv database/
